/*
 * cloth.frag.glsl — the specimen, seen through the cloth (§2 Plate IV).
 *
 * §2: "The cloth's normals drive a refraction of a backdrop texture. That
 * backdrop is the 'specimen': a CC0 macro photograph (botanical or mineral)
 * that is legible only through the distortion. This is the distorted-image
 * requirement, and it is the one place a photograph appears in the whole site."
 *
 * THE REFRACTION IS SPECTRAL, AND IT HAS TO BE
 *
 * §2 Plate II establishes the rule the rest of the piece lives under: all colour
 * in WEFT is produced by refraction, and there is no brand accent. The specimen
 * is a greyscale photograph. If the cloth simply displaced a greyscale sample by
 * the normal, this plate would be the only monochrome one in the sequence — and
 * tinting it would break the rule outright.
 *
 * So the displacement is wavelength-dependent, through the same Cauchy relation
 * Plate II uses: n(λ) = A + B/λ². Each wavelength lands on a slightly different
 * part of the specimen, and where the surface is steep those samples disagree
 * and the disagreement *is* the colour. Flat areas stay grey because every
 * wavelength lands on the same texel. That is exactly how a real refracting
 * surface behaves, and it means the colour in this plate is generated by the
 * same physics as the colour in Plate II rather than by a different mechanism
 * that happens to look similar.
 */

precision highp float;

#include "../lib/spectral.glsl";

uniform sampler2D uSpecimen;
uniform float uWeight;
/** How far a mid-band ray is displaced, in specimen uv. */
uniform float uRefraction;
uniform int uSamples;
/*
 * No uBandWhite here, unlike Plate III. `weftSpectrumResolve` divides the
 * accumulated tristimulus by the flat-spectrum integral the same loop built, so
 * the normalisation is self-contained at whatever sample count the tier gives
 * it — see the WeftSpectrum comment in spectral.glsl. Plate III needs the
 * constant only because a single wavelength has no accompanying flat integral
 * to divide by.
 */
/** Cauchy A and B, from the same endpoints Plate II uses. */
uniform vec2 uCauchy;
/** Scales the specimen under the sheet. Above 1 the photograph is magnified. */
uniform float uSpecimenScale;

varying vec3 vNormal;
varying vec2 vClothUv;
varying float vDepth;

void main() {
  /*
   * The refracted direction, in the plane of the specimen.
   *
   * The full vector form is `refract(incident, normal, eta)`. It is not used
   * here: the incident ray is effectively along −z at this field of view, and
   * for a near-axial ray the in-plane displacement is proportional to the
   * normal's own xy. Using the tangential component directly is that same
   * approximation written so the wavelength dependence is visible in one line
   * instead of buried in an eta that has to be recomputed per sample.
   */
  vec2 tilt = vNormal.xy;

  WeftSpectrum spectrum = weftSpectrumBegin();

  for (int i = 0; i < 32; i++) {
    if (i >= uSamples) break;

    float t = (float(i) + 0.5) / float(uSamples);
    float nm = weftLambdaAt(t);
    float ior = weftCauchyIOR(nm, uCauchy.x, uCauchy.y);

    // (n − 1) is the deviation, exactly as in Plate II's thin-prism form. Blue
    // has the larger index and so is displaced further, which is the direction
    // that makes the fringing read as glass rather than as a filter.
    vec2 offset = tilt * (ior - 1.0) * uRefraction;
    vec2 uv = (vClothUv - 0.5) * uSpecimenScale + 0.5 + offset;

    /*
     * Mirrored rather than clamped or wrapped. Clamping smears the specimen's
     * edge pixels into long streaks wherever the sheet folds near its border;
     * wrapping puts a hard seam through the middle of a fold. Mirroring is
     * continuous across the boundary, so a fold that runs off the specimen
     * simply continues into a reflected copy of it and nothing announces where
     * the photograph ended.
     */
    vec2 mirrored = 1.0 - abs(1.0 - mod(uv, 2.0));

    // `sample` is a reserved word in GLSL ES 3.00; three compiles this shader
    // as 1.00 today, but a name that becomes a syntax error on an upgrade is a
    // trap set for later.
    float value = texture2D(uSpecimen, mirrored).r;
    weftSpectrumAdd(spectrum, nm, value);
  }

  vec3 colour = weftSpectrumResolve(spectrum);

  /*
   * The sheet is lit by how steeply it faces away, not by a light.
   *
   * There is no light source anywhere in this piece — every plate so far is
   * emissive — and adding one here for the cloth alone would make it the only
   * object with a shading model. Facing ratio does the same job with the
   * material's own geometry: a surface turned away from the viewer transmits
   * less, which is Fresnel's observation and needs no light to state.
   */
  float facing = abs(vNormal.z);
  float transmission = mix(0.35, 1.0, facing);

  // Depth falloff, so the far edge of a sheet seen obliquely does not read as
  // brightly as the near one and the plate keeps a sense of volume.
  float depth = 1.0 - smoothstep(3.0, 9.0, vDepth);

  gl_FragColor = vec4(colour * transmission * mix(0.25, 1.0, depth) * uWeight, 1.0);
}
